import type { Metadata } from "next";
import type React from "react";

import { Geist, Geist_Mono } from "next/font/google";
import "@livekit/components-styles";
import "./globals.css";
import { LoginModalWrapper } from "./components/LoginModalWrapper";
import { ThreeBackground } from "./components/ThreeBackground";


import { Suspense } from "react";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import "./globals.css";
import VideoBackground from "./components/VideoBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <script src="https://www.google.com/recaptcha/enterprise.js?render=6LcEEfErAAAAAJoE9c5PrX1uJcAGv6OZx-pY1VYY" async defer />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <ReactQueryProvider>
            <VideoBackground /> 
            {children}
                    <ThreeBackground />
          </ReactQueryProvider>
        </Suspense>

        <LoginModalWrapper />

      </body>
    </html>
  );
}
