import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@livekit/components-styles';
import "./globals.css";
import { LoginModalWrapper } from "./components/LoginModalWrapper";
import { LoginModalTestButton } from "./components/LoginModalTestButton";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <LoginModalWrapper />
        <LoginModalTestButton />
      </body>
    </html>
  );
}
